controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute



Home:
    path: /dashboard
    controller: App\Controller\HomeController::Home
loginForm:
    path: /
    controller: App\Controller\HomeController::index

